["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
lobby = [
    "src/contracts/lobby/lobby.cairo",
]
game = [
    "src/contracts/game/game.cairo",
]


